os:
  - linux
  - osx

dist: trusty
sudo: required
osx_image: xcode7.2

env:
  - THEOS=theos

before_script:
  - git clone --recursive https://github.com/theos/theos.git
  - ./travis/before

script:
 - ./travis/script

compiler:
  - clang
